### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Excelsiorly** [AutoML-4Paradigm/Interstellar#1]
Hi, I've been learning your code lately. After I finished installing the required packages and started running the code by using console : ``` python -W ignore train_align.py```, the error occured:
```
dataset:dbp_wd_15k_V1, seed:1234, search mode:asng
Traceback (most recent call last):
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/series.py", line 1001, in __setitem__
    self._set_with_engine(key, value)
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/series.py", line 1034, in _set_with_engine
    loc = self.index._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 75, in pandas._libs.index.IndexEngine.get_loc
TypeError: '0          True
1          True
2         False
3         False
4          True
          ...  
157155     True
157156    False
157157    False
157158    False
157159    False
Name: h_id, Length: 157160, dtype: bool' is an invalid key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/series.py", line 1021, in __setitem__
    self._where(~key, value, inplace=True)
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/generic.py", line 8794, in _where
    raise InvalidIndexError
pandas.errors.InvalidIndexError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_align.py", line 66, in <module>
    reader.read(data_path=args.data_path)
  File "/home/jojo/PythonProjects/Interstellar-main/EA/read_data.py", line 131, in read
    self.add_align_infor()
  File "/home/jojo/PythonProjects/Interstellar-main/EA/read_data.py", line 160, in add_align_infor
    kb['ah_id'][h_mask] = ent_mapping.loc[kb['ah_id'][h_mask].values]
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/series.py", line 1023, in __setitem__
    self.iloc[key] = value
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/indexing.py", line 670, in __setitem__
    iloc._setitem_with_indexer(indexer, value)
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/indexing.py", line 1790, in _setitem_with_indexer
    value = self._align_series(indexer, Series(value))
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/indexing.py", line 1909, in _align_series
    ser = ser.reindex(obj.axes[0][indexer[0]], copy=True)._values
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/series.py", line 4412, in reindex
    return super().reindex(index=index, **kwargs)
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/generic.py", line 4463, in reindex
    return self._reindex_axes(
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/generic.py", line 4483, in _reindex_axes
    obj = obj._reindex_with_indexers(
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/generic.py", line 4526, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1285, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/home/jojo/anaconda3/envs/pytorch/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3292, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis
```
I have no idea what happened.

Looking forward to your reply.

**Comment by yzhangee** [comment]
Hi,

I have updated the requirement file with the current version I use for the dependencies. Besides, our code is based on python 3.7. Please have a check if you can try our code based on the same setting.
